name: televerseexamples
description: This repository contains examples for the televerse package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  televerse: ^1.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
